controllers:
    resource: ../../src/Controller/
    type: annotation

api_controllers:
    resource: ../../src/ApiBundle/Controller/
    prefix: api
    type: annotation

sky_controllers:
    resource: ../../src/SkyBundle/Controller/
    prefix: api
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
